[package]
name = "gcp-bigquery-client"
version = "0.10.0"
authors = ["Laurent Querel <laurent.querel@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = """
An ergonomic async client library for GCP BigQuery.
"""
homepage = "https://github.com/lquerel/gcp-bigquery-client"
repository = "https://github.com/lquerel/gcp-bigquery-client"
documentation = "https://docs.rs/gcp-bigquery-client"
readme = "README.md"
exclude = ["/.github/*"]
keywords = ["gcp", "bigquery", "google-cloud"]
categories = ["database"]

[dependencies]
yup-oauth2 = "6.0.0"
hyper = "0.14.13"
hyper-rustls = "0.22.1"
thiserror = "1.0.29"
tokio = { version = "1.12.0", features = ["full"] }
reqwest = { version = "0.11.4", features = ["json"] }
url = "2.2.2"
serde = "1.0.130"
serde_json = "1.0.68"
log = "0.4.14"
chrono = "0.4.19"

[dev-dependencies]
tokio-test = "0.4.2"
